a=int(input("enter the values"))
b=int(input("enter the value"))
print("the addition of",a,"+",b, "is: ",(a+b))
print("the subtraction of",a,"+",b, "is: ",a-b)
print("the multiplication of",a,"+",b, "is: ",a*b)
print("the division of",a,"+",b, "is: ",a/b)
print("the floor division of",a,"+",b, "is: ",a//b)